--
AWSTemplateFormatVersion: '2010-09-09'
Parameters:
  S3Bucket:
    Type: String
    Default: ''
  S3Key:
    Type: String
    Default: ''
Resources:
  TagInstance:
    Type: AWS::Lambda::Function
    Properties:
      FunctionName: TagInstanceOwner
      Handler: lambda_function.lambda_handler
      Role: !GetAtt LambdaFunctionRole.Arn
      Code:
        S3Bucket: !Ref S3Bucket
        S3Key: !Ref S3Key
      Runtime: python3.7
      Timeout: 300
  LambdaFunctionRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
        - Effect: Allow
          Principal:
            Service:
              - lambda.amazonaws.com
          Action:
            - sts:AssumeRole
      Path: "/"
      ManagedPolicyArns:
        - "arn:aws:iam::aws:policy/AdministratorAccess"
        - "arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole"
      Policies:
      - PolicyName: STSlambda
        PolicyDocument:
          Version: '2012-10-17'
          Statement:
          - Effect: Allow
            Action: 
              - config:DeleteDeliveryChannel
              - "config:DescribeConfigurationRecorders"
              - "config:DescribeDeliveryChannels"
              - "config:DeleteConfigurationRecorder"
            Resource: '*'
          - Effect: Allow
            Action: 
              - organizations:DescribeAccount
              - organizations:MoveAccount
              - servicecatalog:ProvisionProduct
            Resource: '*'

  EventRule: 
    Type: AWS::Events::Rule
    Properties: 
      Description: "EventRule"
      EventPattern: 
        source: 
          - "aws.ec2"
        detail-type: 
          - "AWS API Call via CloudTrail"
        detail: 
          eventName:
            - "RunInstances"
      State: "ENABLED"
      Targets: 
        - Arn: !GetAtt TagInstance.Arn
          Id: TargetFunctionV1
  PermissionForEventsToInvokeLambda: 
    Type: AWS::Lambda::Permission
    Properties: 
      FunctionName: 
        Ref: TagInstance
      Action: "lambda:InvokeFunction"
      Principal: "events.amazonaws.com"
      SourceArn: !GetAtt EventRule.Arn
